//------------------------------------------//
/*------//Adress Logger by xXRusSXx//-------*/
//------------------------------------------//
//[Date: 24.06  Time: 19:29 ]

//-------------[ Pointers / Bases ]------------//
#define ADR_PlayerPointer                0xB163D0
#define ADR_ServerPointer                0xB10B98
#define ADR_HEALTHPOINTER                0x31FB8
#define ADR_VIEWANGELS                   0xB0FC30
#define ADR_DevicePointer                0xB0FC34
#define ADR_RemotePointer                0xB98120
#define ADR_GlobalPTR                    0xB00C3
#define ADR_StatePTR                     0xB163F8
#define ADR_BasePTR                      0xB48A80
#define ADR_RoomPTR                      0xB16628
#define ADR_HealthPTR                    0x31FB8
#define ADR_UserPTR                      0xB10B98
#define ADR_UserBase                     0xB169F0
#define ADR_MatrixPTR                    0xA9DE50

//----------------[ Offsets ]---------------//
#define ADR_OFS_Speed                    0x8F1D28
#define ADR_OFS_Invisible                0x492AC
#define ADR_OFS_NoSpawntime              0xBB29E0
#define ADR_OFS_LEVEL                    0x49280
#define ADR_OFS_DINAR                    0x49290
#define ADR_OFS_3DPLAYERVIEW             0x101A0
#define ADR_OFS_PLAYERSTATE              0xC4CC
#define ADR_OFS_WEAPONSTATE              0xC4D0
#define ADR_OFS_X                        0x10300
#define ADR_OFS_Y                        0x10310
#define ADR_OFS_Z                        0x10308
#define ADR_OFS_NOSPREAD                 0x10110
#define ADR_OFS_GRAVITY_Z                0xC4B4
#define ADR_OFS_GRAVITY_Y                0xC4B0
#define ADR_OFS_GRAVITY_X                0xC4B8
#define ADR_OFS_NODELAY                  0x10410
#define ADR_OFS_NORELOAD                 0x1040D
#define ADR_OFS_GlobalSize               0xB00
#define ADR_OFS_LocalSize                0x9ECC
#define ADR_OFS_NoReload                 0x1040D
#define ADR_OFS_NoSwitch                 0x1040D
#define ADR_OFS_NoRecoil1                0xC444
#define ADR_OFS_NoRecoil2                0xC448
#define ADR_OFS_NoRecoil3                0xC44C
#define ADR_OFS_NFD                      0x102E8
#define ADR_OFS_ViewMain                 0x101D4
#define ADR_OFS_ViewX                    0x101D4
#define ADR_OFS_ViewZ                    0x101D8
#define ADR_OFS_ViewY                    0x101DC
#define ADR_OFS_Slot5                    0x3065C
#define ADR_OFS_Slot6                    0x3065D
#define ADR_OFS_Slot7                    0x3065E
#define ADR_OFS_Slot8                    0x3065F
#define ADR_OFS_PlayerState              0xC4CC
#define ADR_OFS_WeaponMain               0x101EC
#define ADR_OFS_Weapon1                  0x101EC
#define ADR_OFS_Weapon2                  0x101EE
#define ADR_OFS_Weapon3                  0x101F0
#define ADR_OFS_UserName                 0x4931C
#define ADR_OFS_Invisible                0x492AC
#define ADR_OFS_Pitch                    0x101A8
#define ADR_OFS_Yaw                      0x101C4
#define ADR_OFS_PlayerView               0x101A0
#define ADR_OFS_PlayerSpeed              0x1010C
#define ADR_OFS_NoSpread                 0x10110
#define ADR_OFS_RoomMaster               0x2DA7C
#define ADR_OFS_Premium1                 0x58C
#define ADR_OFS_Premium2                 0x3CC
#define ADR_OFS_WeaponDamage             0x8C
#define ADR_OFS_WeaponDefence            0x5130
#define ADR_OFS_WeaponRange              0x0
#define ADR_OFS_AmmoNumber               0x94
#define ADR_OFS_MagazineNumber           0x98
#define ADR_OFS_EffectRange              0x9C
#define ADR_OFS_Parabola                 0xA0
#define ADR_OFS_ShotSpeed                0xB0
#define ADR_OFS_WeaponWheight            0xB4
#define ADR_OFS_DevicePTR                0x2B930
#define ADR_OFS_Mouse                    0xB0FC60

//---------------[ Adresses ]---------------//
#define ADR_SpawnTime                    0xBB29E0
#define ADR_UnlAmmo                      0xB10050
#define ADR_NoSpawn1                     0xBB29E0
#define ADR_NoSpawn2                     0xBB29E4
#define ADR_NoSpawn3                     0xBB29E8
#define ADR_NoBounds1                    0xBB29E8
#define ADR_NoBounds2                    0xBB29EC
#define ADR_NoBounds3                    0xBB29F0
#define ADR_NoWater1                     0xB1D1EC
#define ADR_NoWater2                     0xB1D1F0
#define ADR_WTW                          0x8BB190
#define ADR_FastLockOn                   0xAA7DCC
#define ADR_SuperNoSpread                0x8F19A8
#define ADR_PlantAnyWhere                0xB0FC6E
#define ADR_DefuseAnyWhere               0x960A0C
#define ADR_AutoRepair                   0xB0FC77
#define ADR_Scope                        0x9609F0
#define ADR_Artilery                     0x8F1AA0
#define ADR_FastHealth                   0xB1A9E4
#define ADR_FastAmmo                     0xB1A9DC
#define ADR_FastFlag                     0xB1A9EC
#define ADR_WUW                          0xB1D1F4
#define ADR_UnlAmmo                      0xB10050
#define ADR_Boneshot                     0x8F2980
#define ADR_STW                          0x8B477C
#define ADR_Speed                        0x8F1D28
#define ADR_DeathCam                     0xBB16B4
#define ADR_Explosion                    0x8F1B18
#define ADR_PlayerProne                  0xB169D8
#define ADR_StaminaRefill                0xA97A20
#define ADR_AntiRadar                    0xB1D224
#define ADR_QuickPlant                   0xB0FC54
#define ADR_BigCarName                   0x8F1B80
#define ADR_AutoStart                    0x54F1F7
#define ADR_WeaponShot1                  0xB16420
#define ADR_WeaponShot2                  0xB16440
#define ADR_Breaklimit                   0x8F1910
#define ADR_FullBright1                  0xB1689C
#define ADR_FullBright2                  0xB168A0
#define ADR_FullBright3                  0xB168A4
#define ADR_GlassWalls                   0xB0FD2C
#define ADR_WeaponGravity                0x8F1968
#define ADR_SilentWalk                   0xBA84E8
#define ADR_LadderSpeed                  0x8F1CF0
#define ADR_CrossHair                    0xB1AA00
#define ADR_ColorShot                    0xB1689C
#define ADR_DeadSpinner                  0x95D814
#define ADR_HideWeapon                   0x8F19EC
#define ADR_ChangeRoll                   0x8F1A20
#define ADR_WTH                          0x8B21DC
#define ADR_RollSpeed                    0x8F1B60
#define ADR_VirtualJump                  0x8F19D4
#define ADR_Drunk                        0xB10004
#define ADR_SniperAmmo                   0xB0FC95
#define ADR_ExtraAmmo1                   0xB0FC93
#define ADR_ExtraAmmo2                   0xB0FC94
#define ADR_AssaultAmmo                  0xB0FC97
#define ADR_Bandage                      0xB0FC99
#define ADR_ClanTag1                     0xB34B50
#define ADR_ClanTag2                     0xB34B0C
#define ADR_ClanTag3                     0xB34B58
#define ADR_ClanTag4                     0xB335D4
#define ADR_ClanTag5                     0xACC684
#define ADR_ClanTag6                     0xB490F4
#define ADR_RoomMaster                   0x492AC
#define ADR_Swim1                        0xB16414
#define ADR_Swim2                        0xB16410
#define ADR_CqcProne                     0x9609DC
#define ADR_Disable_KickMesssage2        0xFFEF52DA
#define ADR_GameMode                     0x9609E4
#define ADR_Packet                       0x2AB20

//----------------[ User ]-----------------//

#define ADR_User_Health                  0x984
#define ADR_User_Name                    0x62C
#define ADR_User_Points                  0x4820
#define ADR_User_Ping                    0x700

//-----------------[ D3D ]------------------//
#define ADR_D3DUserName                  0xB490AC

//--------------[ WeaponBinder ]-------------//

#define ADR_ClassBase                    0xB49410
#define ADR_WeaponBase                   0xB34BB0
#define ADR_OFS_SlotBase                 0x2F4B8

//-----------------[ ASM ]-----------------//

#define ADR_ASM_QuickDefuse              0x43B147
#define ADR_ASM_Bullets                  0x5129C3
#define ADR_ASM_WTW                      0x77E7E2
#define ADR_ASM_STW                      0x645350
#define ADR_ASM_BackToLobby              0x4E2BCC
#define ADR_ASM_AlwaysCrossHair          0x58205B
#define ADR_ASM_EngineText               0x52215E
#define ADR_ASM_MessageBox               0x4BD8C6
#define ADR_ASM_UnlAmmo                  0x5A555C
#define ADR_ASM_SwitchTime               0x518890
#define ADR_ASM_OPK                      0x4081A4
#define ADR_ASM_AutoStart                0x54F1F7
#define ADR_ASM_SuperCarSound            0x4275CA
#define ADR_ASM_DamageAs                 0x512C88
#define ADR_ASM_VehJump1                 0x45E923
#define ADR_ASM_VehJump2                 0x45E92B
#define ADR_ASM_VehNoDamage              0x42AB93
#define ADR_ASM_SuperCar1                0x427565
#define ADR_ASM_SuperCar2                0x427590
#define ADR_ASM_SuperCar3                0x4275D0
#define ADR_ASM_STW1                     0x613170
#define ADR_ASM_STW2                     0x613176
#define ADR_ASM_EventRoom                0x401EA7
#define ADR_ASM_EventRoom2               0x52B634
#define ADR_ASM_AiKnifeRoom              0x41D191
#define ADR_ASM_UnlOxygen                0x50C479
#define ADR_ASM_Artillery0               0x4FACA6
#define ADR_ASM_Artillery1               0x0
#define ADR_ASM_Artillery2               0x5A1415
#define ADR_ASM_Artillery3               0x5A14A8
#define ADR_ASM_Artillery4               0x5A11F0
#define ADR_ASM_Artillery5               0x582631
#define ADR_ASM_Artillery6               0x5A138F
#define ADR_ASM_Artillery7               0x5A1525
#define ADR_ASM_UserKill                 0x417364
#define ADR_ASM_FakeKick                 0x59AA4B
#define ADR_ASM_SpamBot                  0x521B07
#define ADR_ASM_OPK1                     0x4081AC
#define ADR_ASM_OPK2                     0x4081B5
#define ADR_ASM_OPK3                     0x4081C1
#define ADR_ASM_AntiOverHeat             0x733416
#define ADR_ASM_AutoRepair1              0x4275EB
#define ADR_ASM_AutoRepair2              0x42761A
#define ADR_ASM_AutoRepair3              0x427696
#define ADR_ASM_AutoAmmo1                0x50A464
#define ADR_ASM_AutoAmmo2                0x50A4A4
#define ADR_ASM_AutoHeal1                0x50A56F
#define ADR_ASM_AutoHeal2                0x50A7DC
#define ADR_ASM_NoRestriction            0x0

//----------------[ AntiAbnormal ]-----------------//
#define ADR_AntiAbnormal1                0x124
#define ADR_AntiAbnormal2                0x125
#define ADR_AntiAbnormal3                0x360
#define ADR_AntiAbnormal4                0x361

//----------------[ DrawIndexPrimitive ]-----------------//
#define ADR_ASM_HOOK1                    0x0
#define ADR_ASM_HOOK2                    0x4
#define ADR_ASM_EngineDipCall1           0x794CA0
#define ADR_ASM_EngineDipCall2           0x796170
#define ADR_ASM_EngineDipCall3           0x794F20
#define ADR_ASM_EngineDipCall4           0x505CEB
#define ADR_ASM_EngineDipCall5           0x7961C0
#define ADR_EngineDipVar1                0xA9E350
#define ADR_ASM_EngineDipVar2            0x7D152B
#define ADR_ASM_EndsceneReturn           0x6D4101
#define ADR_ASM_FuncStart                0x7D1320

//---------------[ BypassWR ]---------------//
#define ADR_WarRockCheck2                0x5E8781
#define ADR_WarRockCheck3                0x51F954
#define ADR_CRCPatch                     0x4196D5

//Addresses Logged: 215 >< Addresses Failed: 4//
//---Special Thanks to:  Kazbah, Exodus, CyberRazzer, etc---//

